/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by src/scripts/build-pure-registry.ts
// Do not edit this file directly.
import * as React from "react"


export const Index: Record<string, any> = {
  "badge-shadcn": {
    name: "badge-shadcn",
    description: "A customizable badge component",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["class-variance-authority","clsx","tailwind-merge","@radix-ui/react-slot"],
    files: [{
      path: "src/registry/pure-ui/components/shadcn/ui/badge/index.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pure-ui/components/shadcn/ui/badge/index.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "badge-demo": {
    name: "badge-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["@pure-ui/components/badge-shadcn"],
    dependencies: undefined,
    files: [{
      path: "src/registry/pure-ui/components/shadcn/examples/badge/badge-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pure-ui/components/shadcn/examples/badge/badge-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "badge-as-link-demo": {
    name: "badge-as-link-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["@pure-ui/components/badge-shadcn"],
    dependencies: undefined,
    files: [{
      path: "src/registry/pure-ui/components/shadcn/examples/badge/shadcn-badge-as-link-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pure-ui/components/shadcn/examples/badge/shadcn-badge-as-link-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "badge-sizes-demo": {
    name: "badge-sizes-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["@pure-ui/components/badge-shadcn"],
    dependencies: undefined,
    files: [{
      path: "src/registry/pure-ui/components/shadcn/examples/badge/shadcn-badge-sizes-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pure-ui/components/shadcn/examples/badge/shadcn-badge-sizes-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }